import { useNavigate } from "react-router-dom";

function landing(){
    const navigate = useNavigate();
    function login(){
        alert("You have login");
        window.location.href='';
    }

    function register(){
        alert("you have registered");
    }

    return (
        <div className="">
            <div className="flex justify-between items-center px-4 py-2">
                <div><h1 className="text-3xl font-bold">This is Landing Page</h1></div>
                <div className="flex space-x-4">
                    <p className="bg-amber-50 p-2 text-black rounded-ee-xl cursor-pointer" onClick={()=>navigate("/login")}>Login</p>
                    <p className="bg-amber-50 p-2 text-black rounded-ee-xl cursor-pointer" onClick={()=>navigate("/register")}>Register</p>
                </div>
                
            </div>
            <div className="flex flex-col items-center mt-10">
                <h1 className="text-2xl full"><span className="text-yellow-300 font-extrabold">Hello 👋, </span>Welcome to website</h1>

                <div className="mt-4">
                    <p>Get score, recommendations generated by AI</p>
                </div>

                <div>
                    <img src="https://th.bing.com/th/id/OIP.3R6-cLf_Mw7_gP3de0auqgHaEO?w=275&h=180&c=7&r=0&o=7&dpr=1.1&pid=1.7&rm=3" alt="" className="w-2xl m-3"/>
                </div>

                <div className="flex gap-2  ">
                    <p className="bg-amber-50 p-2 space- text-black rounded-ee-xl cursor-pointer" onClick={login}>Login</p>
                    <p className="bg-amber-50 p-2 space- text-black rounded-ee-xl cursor-pointer" onClick={register}>Register</p>
                </div>
            </div>
        </div>
        
    )
}

export default landing